# Generated by Django 3.2 on 2021-04-30 16:45

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_skill', models.CharField(choices=[('n', '----------'), ('s', 'Soft'), ('h', 'Hard')], default='n', max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('avatar', stdimage.models.StdImageField(blank=True, null=True, upload_to='img/skills/')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
